{{- if or .Values.app.key .Values.database.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "databasement.fullname" . }}
  labels:
    {{- include "databasement.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if and .Values.app.key (not .Values.app.existingSecret) }}
  app-key: {{ .Values.app.key | b64enc | quote }}
  {{- end }}
  {{- if and .Values.database.password (not .Values.database.existingSecret) (ne .Values.database.connection "sqlite") }}
  db-password: {{ .Values.database.password | b64enc | quote }}
  {{- end }}
{{- end }}
