apiVersion: v2
name: databasement
description: A Helm chart for Databasement - Database backup management application
type: application
version: 0.1.15
appVersion: "0.1.15"
keywords:
  - database
  - backup
  - mysql
  - postgresql
  - mariadb
home: https://david-crty.github.io/databasement/
sources:
  - https://github.com/David-Crty/databasement
maintainers:
  - name: David-Crty
    email: david_courtey@yahoo.com
annotations:
  artifacthub.io/license: MIT
  artifacthub.io/readme: README.md
